import type {createBuilder} from '../src/assembly/world';
import {PART_BY_ID} from '../src/assembly/catalog';
import {worldPort} from '../src/assembly/snapping';
export async function verifyBuilder(builder:Awaited<ReturnType<typeof createBuilder>>){
 const check=(condition:unknown,message:string)=>{if(!condition)throw new Error(message);};
 const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
 const move=(p:{clientX:number;clientY:number})=>window.dispatchEvent(new PointerEvent('pointermove',{...p,bubbles:true,pointerId:1}));
 const drop=()=>window.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:1}));
 const begin=(name:string)=>{const el=document.querySelector(`[aria-label="Drag ${name}"]`)!;const r=el.getBoundingClientRect();el.dispatchEvent(new PointerEvent('pointerdown',{clientX:r.x+r.width/2,clientY:r.y+r.height/2,bubbles:true,button:0,pointerId:1}));};
 await wait(100);
 begin('Support base');move(builder.project([0,47,0]));drop();await wait(1600);
 let state=builder.inspect();check(state.items.length===1,'Tray drag did not create a base');const base=state.items[0];check(base.position[1]<10,'Unconnected base did not fall');
 const target=worldPort(PART_BY_ID.base.ports[0],{position:base.position,yaw:0});
 begin('Spacer');move(builder.project(target));await wait(50);drop();await wait(200);
 state=builder.inspect();check(state.connections.length===1,'Spacer failed to snap onto base');check(state.items.every(i=>i.fixed),'Connected pieces were not held');
 // A cancelled tray drag must not leak an instance or a body.
 begin('Snake ramp');builder.cancel();check(builder.inspect().items.length===2,'Cancel leaked a part');
 // Pick through the instanced mesh, rotate upright, then release away from any connector.
 const spacer=state.items.find(i=>i.kind==='spacer')!,pick=builder.project([spacer.position[0]+8,spacer.position[1]+30,spacer.position[2]]);
 const canvas=document.querySelector('.assembly-world canvas')!;
 canvas.dispatchEvent(new PointerEvent('pointerdown',{...pick,bubbles:true,button:0,pointerId:1}));
 drop();check(builder.inspect().selected===spacer.id,'Click did not select spacer');
 canvas.dispatchEvent(new PointerEvent('pointerdown',{...pick,bubbles:true,button:0,pointerId:1}));move({clientX:pick.clientX+8,clientY:pick.clientY});
 check(builder.inspect().holding===spacer.id,'Instanced picking did not find the spacer');
 move(builder.project([500,100,0]));builder.rotate(Math.PI/4);drop();await wait(1800);
 state=builder.inspect();check(state.connections.length===0,'Pickup left a stale connection');check(state.items.find(i=>i.id===spacer.id)!.position[1]<80,'Released spacer did not fall');
 // Place a second base deliberately 6 mm off the ideal span. The support
 // guide must correct the spacing so a bridge then catches both ends.
 const firstBase=state.items.find(i=>i.kind==='base')!;
 const firstTop=worldPort(PART_BY_ID.base.ports[0],{position:firstBase.position,yaw:0});
 const span=Math.hypot(138,24);
 begin('Support base');move(builder.project([firstTop[0]+span+6,82,firstTop[2]]));drop();await wait(1500);
 begin('Standard ramp');move(builder.project(firstTop));await wait(80);
 check(document.querySelector('[role="status"]')!.textContent!.startsWith('2 connectors'), 'Bridge did not align both supports: '+JSON.stringify(builder.inspect()));
 drop();await wait(200);check(builder.inspect().connections.length===2,'Two-ended drop did not create both connections');
 const ramp=builder.inspect().items.find(i=>i.kind==='ramp')!;
 const {Vector3,Quaternion}=await import('three/webgpu');
 const {columnsFor}=await import('../src/assembly/pivot');
 const columns=columnsFor(PART_BY_ID.ramp.ports);
 const at=(item:typeof ramp,p:number[])=>new Vector3(...p).applyQuaternion(new Quaternion(...item.rotation)).add(new Vector3(...item.position));
 const click=builder.project(at(ramp,columns[1].position).toArray());
 canvas.dispatchEvent(new PointerEvent('pointerdown',{...click,bubbles:true,button:0,pointerId:1}));drop();
 check(builder.inspect().selected===ramp.id,'Ramp click did not select');
 builder.selectColumn(1);
 const before=at(ramp,columns[1].position);
 builder.setAngle(37.3);
 const after=builder.inspect().items.find(i=>i.id===ramp.id)!;
 check(before.distanceTo(at(after,columns[1].position))<1e-8,'Rotation moved selected column');
 check(builder.inspect().connections.length===1,'Rotation did not retain only the pivot connection');
 check(!builder.inspect().holding,'Selection started a move');
 await wait(100);
 const dropButton=document.querySelector<HTMLButtonElement>('.drop-marble:not([hidden])');
 check(dropButton&&!dropButton.disabled,'Open inlet has no usable drop button');
 dropButton!.click();
 check(builder.inspect().marbles.length===1,'Drop button did not spawn a marble');
 dropButton!.click();
 check(builder.inspect().marbles.length===1,'Occupied inlet allowed an overlapping marble');
 const spawnY=builder.inspect().marbles[0][1];await wait(300);
 check(builder.inspect().marbles[0][1]<spawnY,'Spawned marble did not fall');
 // Cover the inlet with a spacer, then select the ramp again.
 const {inputColumns}=await import('../src/assembly/drop');
 const top=inputColumns('ramp')[0].port.position;
 begin('Spacer');move(builder.project(at(after,top).toArray()));await wait(50);drop();await wait(100);
 const outletClick=builder.project(at(after,columns[1].position).toArray());
 canvas.dispatchEvent(new PointerEvent('pointerdown',{...outletClick,bubbles:true,button:0,pointerId:1}));drop();await wait(100);
 check(builder.inspect().selected===ramp.id,'Could not reselect covered ramp');
 check(!document.querySelector('.drop-marble:not([hidden])'),'Covered inlet still offered marble drop');
 const support=builder.inspect().items.filter(i=>i.kind==='spacer'&&i.fixed).at(-1)!;
 const supportTop=PART_BY_ID.spacer.ports.find(p=>p.axis===1)!;
 begin('Paddle wheel');move(builder.project(at(support,supportTop.position).toArray()));await wait(80);drop();await wait(100);
 const paddle=builder.inspect().items.find(i=>i.kind==='paddle')!;
 check(paddle.fixed,'Paddle did not attach to support');
 const {PADDLE,paddleAxleY}=await import('../src/pieces/paddle-wheel');
 const paddleClick=builder.project(at(paddle,[PADDLE.x,paddleAxleY,PADDLE.z]).toArray());
 canvas.dispatchEvent(new PointerEvent('pointerdown',{...paddleClick,bubbles:true,button:0,pointerId:1}));drop();await wait(100);
 check(builder.inspect().selected===paddle.id,'Could not select paddle');
 document.querySelector<HTMLButtonElement>('.drop-marble:not([hidden])')!.click();
 let turned=false;
 for(let i=0;i<30;i++){await wait(50);if(Math.abs(builder.inspect().wheels.find(w=>w.id===paddle.id)!.angle)>.1)turned=true;}
 check(turned,'Assembly paddle wheel did not turn after a marble drop');
 const paddleNow=builder.inspect().items.find(i=>i.id===paddle.id)!;
 const paddleInlet=inputColumns('paddle')[0];
 begin('Starting gate');move(builder.project(at(paddleNow,paddleInlet.port.position).toArray()));await wait(80);drop();await wait(100);
 const starter=builder.inspect().items.find(i=>i.kind==='start')!;
 check(starter.fixed,'Starting gate did not attach');
 const {START}=await import('../src/pieces/start');
 const gateClick=builder.project(at(starter,[START.pivotX,START.pivotY,0]).toArray());
 canvas.dispatchEvent(new PointerEvent('pointerdown',{...gateClick,bubbles:true,button:0,pointerId:1}));drop();await wait(100);
 check(builder.inspect().selected===starter.id,'Could not select starting gate');
 const fill=[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent==='Fill all slots')!;
 const beforeFill=builder.inspect().marbles.length;fill.click();
 check(builder.inspect().marbles.length===beforeFill+6,'Fill all slots did not create six marbles');
 check(new Set(builder.inspect().marbleColors.slice(-6)).size===6,'Gate fill colors were not varied');
 await wait(1500);fill.click();check(builder.inspect().marbles.length===beforeFill+6,'Fill duplicated occupied slots');
 [...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent==='Release')!.click();
 await wait(1000);check(builder.inspect().gates.find(g=>g.id===starter.id)!.angle<-.6,'Release did not tip starting gate');
 const previous=builder.inspect().items.map(i=>({id:i.id,kind:i.kind}));
 builder.loadPreset('split-rejoin');await wait(150);
 check(builder.inspect().items.length===10,'Preset did not replace the layout');
 check(builder.inspect().marbles.length===0,'Preset retained old marbles');
 check(builder.inspect().items.every(i=>i.fixed),'Preset has unsupported loose parts');
 check(builder.inspect().selected===builder.inspect().items.find(i=>i.kind==='start')!.id,'Preset did not select its gate');
 builder.fillGate();check(builder.inspect().marbles.length===6,'Preset gate cannot be filled');
 builder.restorePrevious();await wait(100);
 check(JSON.stringify(builder.inspect().items.map(i=>({id:i.id,kind:i.kind})))===JSON.stringify(previous),'Preset restore lost previous pieces');
 check(builder.inspect().marbles.length===0,'Restore retained preset marbles');
 const out=document.createElement('output');out.id='assembly-test-result';out.textContent='PASS: tray drag, free fall, connector snap, cancellation, instanced pickup, rotation, disconnect, release, support spacing two-ended bridge, column selection free pivot rotation inlet marble dropping paddle rotation and colored gate fill/release';out.style.cssText='position:fixed;top:150px;left:28px;z-index:20;background:#e8ffd8;padding:10px';document.body.appendChild(out);
}
