import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {PRESETS} from './assembly/presets';
import {hasPackedPreset} from './assembly/preset-stock';
import {PARTS} from './assembly/catalog';
import {createBuilder,type BuilderState} from './assembly/world';
import {DEFAULT_MARBLE_OUTLINE} from './assembly/marble-outline';
import './assembly.css';
function Assembly(){
 const host=useRef<HTMLDivElement>(null),builder=useRef<Awaited<ReturnType<typeof createBuilder>>|undefined>(undefined);
 const [state,setState]=useState<BuilderState>({message:'Loading parts…',holding:false,count:0});
 const [preset,setPreset]=useState(PRESETS[0].id);
 const [constructionSpeed,setConstructionSpeed]=useState(1);
 const packedAvailable=hasPackedPreset(PRESETS.find(p=>p.id===preset)!);
 const [outline,setOutline]=useState(DEFAULT_MARBLE_OUTLINE);
 const busy=!!(state.fillingTub||state.dumpingTub||state.constructing);
 const [thumbnails,setThumbnails]=useState<Record<string,string>>({});const [ready,setReady]=useState(false);
 useEffect(()=>{let stopped=false;createBuilder(host.current!,s=>{if(!stopped)setState(s);},(id,url)=>{if(!stopped)setThumbnails(t=>({...t,[id]:url}));}).then(b=>{if(stopped)b.dispose();else{builder.current=b;setReady(true);
 const verify=new URLSearchParams(location.search).get('verify');if(import.meta.env.DEV&&verify!==null&&verify!=='tub')(verify==='performance'?import('../tests/assembly-performance').then(m=>m.prepareAssemblyPerformance(b)):verify==='render'?import('../tests/render-preset-video').then(m=>m.preparePresetVideo(b)):verify==='video'?import('../tests/video-benchmark-browser').then(m=>m.prepareVideoBenchmark(b)):verify==='follow'?import('../tests/marble-follow-browser').then(m=>m.verifyMarbleFollow(b)):verify==='construct'?import('../tests/construction-browser').then(m=>m.verifyConstruction(b)):verify==='dump'?import('../tests/tub-dump-browser').then(m=>m.verifyTubDump(b)):import('../tests/assembly-browser').then(m=>m.verifyBuilder(b))).catch(e=>setState({message:'TEST FAILED: '+e.message,holding:false,count:0}));}}).catch(e=>setState({message:`Could not load builder: ${e.message}`,holding:false,count:0}));return()=>{stopped=true;builder.current?.dispose();};},[]);
 return <main className="builder">
  <div className="assembly-world" ref={host}/>
  <header className="assembly-header"><div><span>MARBLEWORKS</span><h1>Build a run</h1></div><div className="preset-controls"><select disabled={busy} aria-label="Maze preset" value={preset} onChange={e=>setPreset(e.target.value)}>{PRESETS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={!ready||busy} onClick={()=>builder.current?.loadPreset(preset,'built')}>Load built</button><button disabled={!ready||busy||!packedAvailable} title={packedAvailable?'Load this kit loose in the tub':'No packed layout available for this preset'} onClick={()=>builder.current?.loadPreset(preset,'packed')}>Load in tub</button><button disabled={!ready||state.fillingTub||state.dumpingTub} onClick={()=>state.constructing?builder.current?.stopConstruction():builder.current?.constructPreset(preset)}>{state.constructing?`Stop construction (${state.constructing.completed}/${state.constructing.total})`:'Construct preset'}</button><label className="construction-speed">Build speed <input aria-label="Build speed" type="range" min="0.25" max="10" step="0.25" value={constructionSpeed} disabled={!ready} onChange={e=>{const speed=Number(e.target.value);setConstructionSpeed(speed);builder.current?.setConstructionSpeed(speed);}}/><output>{constructionSpeed}×</output></label><button disabled={!ready||state.fillingTub} onPointerUp={e=>e.stopPropagation()} onClick={()=>builder.current?.randomizeColors()}>Randomize colors</button><button disabled={!ready||busy} onClick={()=>builder.current?.dumpTub()}>{state.dumpingTub?'Dumping…':'Dump tub'}</button><button disabled={!ready||busy} onClick={()=>builder.current?.refillTub()}>{state.fillingTub?'Filling tub…':'Refill tub'}</button>{state.canRestore&&<button disabled={busy} onClick={()=>builder.current?.restorePrevious()}>Restore previous layout</button>}<a href="/components.html">Component previews ↗</a></div></header>
  <div className="assembly-status" role="status">{state.message}</div>
  <fieldset className="marble-outline-controls" disabled={!ready||state.fillingTub}><legend>Marble outline</legend>{(['inside','outside'] as const).map(side=><label key={side}><span>{side==='inside'?'Inside':'Outside'}</span><input aria-label={`${side==='inside'?'Inside':'Outside'} outline width`} type="range" min="0" max="8" step="0.5" value={outline[side]} onChange={e=>{const next={...outline,[side]:Number(e.target.value)};setOutline(next);builder.current?.setMarbleOutline(next.inside,next.outside);}}/><output>{outline[side]} px</output></label>)}</fieldset>
  <aside className="assembly-tools"><span>{state.count} pieces</span>{state.selected&&<div className="rotation-panel"><strong>{state.selected.name}</strong>{state.selected.kind==='start'&&<div className="gate-actions"><button onClick={()=>builder.current?.fillGate()}>Fill all slots</button><button onClick={()=>builder.current?.releaseGate()}>Release</button><button onClick={()=>builder.current?.closeGate()}>Close gate</button></div>}<div className="column-choices"><span>Rotate about</span>{Array.from({length:state.selected.columns},(_,i)=><button key={i} aria-pressed={state.selected!.column===i} onClick={()=>builder.current?.selectColumn(i)}>Column {i+1}</button>)}</div><label>Angle <input aria-label="Rotation angle" type="range" min="-180" max="180" step="0.1" value={state.selected.angle} onChange={e=>builder.current?.setAngle(Number(e.target.value))}/><output>{state.selected.angle.toFixed(1)}°</output></label><small>Click a column or its gold marker, then drag the green ring.</small></div>}{state.holding&&<><button onPointerDown={e=>e.stopPropagation()} onClick={()=>builder.current?.rotate(-Math.PI/12)}>↶ 15°</button><button onPointerDown={e=>e.stopPropagation()} onClick={()=>builder.current?.rotate(Math.PI/12)}>↷ 15°</button><button onClick={()=>builder.current?.lift(47)}>↑ One level</button><button onClick={()=>builder.current?.lift(-47)}>↓ One level</button><button onClick={()=>builder.current?.cancel()}>Cancel</button></>}</aside>
  <section className="parts-tray" aria-label="Parts tray"><div className="tray-label">PARTS <span>Drag into the world</span></div><div className="parts-scroll">{PARTS.map(p=><button key={p.id} disabled={!ready||busy} aria-label={`Drag ${p.name}`} className="tray-part" onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();builder.current?.begin(p.id,e.nativeEvent);}}>{thumbnails[p.id]?<img src={thumbnails[p.id]} alt="" draggable={false}/>:<span className="part-placeholder">◌</span>}<span>{p.name}</span></button>)}</div></section>
  <div className="assembly-help">Click to select · choose a column and drag its ring to rotate · drag a piece to move · empty space orbits · right-drag pans</div>
 </main>;
}
createRoot(document.getElementById('root')!).render(<Assembly/>);
